In [ ]:
import cv2
#Creat a cascade classifier object
face_cascade = cv2.CascadeClassifier("/Users/priyambasu/desktop/haarcascade_frontalface_default.xml")
#Reading image as it is
img = cv2.imread("/Users/priyambasu/desktopReal_madrid", 1)
#Reading image as gray scale
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
#Search co-ordinates of image
faces = face_cascade.detectMultiScale(gray_img, scaleFactor = 1.05, minNeighbors = 5)
print(type(faces))
print(faces)

for x,y,w,h in faces:
    img = cv2.rectangle(img, (x,y), (x+w, y+h), (0, 255, 0), 3)
    
cv2.imshow("Gray", img)

cv2.waitKey(0)

cv2.destroyAllWindows()

<class 'numpy.ndarray'>
[[ 285  382   41   21]
 [ 195  186   55   28]
 [ 468  194   43   22]
 [ 161  337  129   64]
 [  79  204   43   22]
 [ 548  213   41   20]
 [1094  206   58   29]
 [ 211  493  223  112]
 [ 353  360  118   59]
 [ 968  591   50   25]
 [ 227  217   95   47]
 [ 905  654   77   38]
 [ 747  582   81   40]
 [ 301  218   95   47]
 [ 428  225   56   28]
 [ 635  427   55   28]
 [ 689  569   76   38]
 [ 370  446   54   27]
 [ 776   88  271  135]
 [ 888  604   81   40]
 [ 851  560   92   46]
 [ 539  406   75   37]
 [ 142  217  102   51]
 [ 457  219   78   38]
 [  84  181   74   37]
 [ 742  182  124   62]
 [ 812  388   83   41]
 [ 319  112   91   46]
 [ 788   67   90   45]
 [ 777  414  202  101]
 [ 544  627  172   86]
 [ 210   61   48   24]
 [ 705  231   82   41]
 [ 190   83   88   44]
 [ 392  249   97   48]
 [ 452   61   68   34]
 [ 157  179  139   70]
 [ 151  496  101   50]
 [ 430  439  123   62]
 [ 946  688   46   23]
 [1019  586   78   39]
 [1030  650   96   48]
 [ 630  45